import { useEffect, useMemo, useState } from "react";

import type { Lead, Meeting } from "../types";

type Draft = { meeting_url: string; admin_note: string };
type Props = { meetings: Meeting[]; leads: Lead[]; actionLoading: string; onDelete: (id: number) => Promise<void>; onSave: (id: number, draft: Draft) => Promise<void>; onNotify: (id: number) => Promise<void> };

export default function MeetingsView({ meetings, leads, actionLoading, onDelete, onSave, onNotify }: Props) {
  const leadMap = useMemo(() => new Map(leads.map((lead) => [lead.id, lead])), [leads]);
  const [drafts, setDrafts] = useState<Record<number, Draft>>({});
  const meetingSignature = meetings.map((meeting) => `${meeting.id}:${meeting.meeting_url}:${meeting.admin_note}:${meeting.notified_at}`).join("|");
  useEffect(() => setDrafts(Object.fromEntries(meetings.map((meeting) => [meeting.id, { meeting_url: meeting.meeting_url ?? "", admin_note: meeting.admin_note ?? "" }]))), [meetingSignature]);
  const ordered = [...meetings].sort((a, b) => new Date(a.starts_at).getTime() - new Date(b.starts_at).getTime());
  function change(id: number, field: keyof Draft, value: string) { setDrafts((current) => ({ ...current, [id]: { ...(current[id] ?? { meeting_url: "", admin_note: "" }), [field]: value } })); }
  return <><section className="page-heading"><div><span className="section-kicker">Agenda comercial</span><h1>Reuniões agendadas</h1><p>Complete os dados da chamada e avise o participante quando tudo estiver pronto.</p></div></section><section className="meeting-grid">{ordered.map((meeting) => { const lead = leadMap.get(meeting.lead_id); const startsAt = new Date(meeting.starts_at); const draft = drafts[meeting.id] ?? { meeting_url: "", admin_note: "" }; return <article className="panel meeting-card" key={meeting.id}><div className="panel-header"><div><span className="section-kicker">{startsAt.toLocaleDateString("pt-BR")}</span><h2>{startsAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</h2></div><span className="status-pill meeting_booked">{meeting.notified_at ? "Participante avisado" : "Aguardando detalhes"}</span></div><div className="meeting-person"><strong>{lead?.name ?? `Participante #${meeting.lead_id}`}</strong><span>{lead?.email}</span><small>{lead?.company} · {lead?.role}</small></div><label>Link da chamada<input type="url" value={draft.meeting_url} placeholder="https://meet.google.com/..." onChange={(event) => change(meeting.id, "meeting_url", event.target.value)} /></label><label>Orientações adicionais<textarea value={draft.admin_note} placeholder="Ex.: duração de 30 minutos" onChange={(event) => change(meeting.id, "admin_note", event.target.value)} /></label><div className="meeting-actions"><button className="secondary-button" disabled={actionLoading === `save-meeting-${meeting.id}`} onClick={() => onSave(meeting.id, draft)}>{actionLoading === `save-meeting-${meeting.id}` ? "Salvando..." : "Salvar detalhes"}</button><button className="primary-button" disabled={!draft.meeting_url || actionLoading === `notify-meeting-${meeting.id}`} onClick={() => onNotify(meeting.id)}>{actionLoading === `notify-meeting-${meeting.id}` ? "Enviando..." : meeting.notified_at ? "Avisar novamente" : "Avisar participante"}</button><button className="danger-button" disabled={actionLoading === `delete-meeting-${meeting.id}`} onClick={() => onDelete(meeting.id)}>Excluir</button></div></article>; })}{ordered.length === 0 && <div className="panel empty-state">Nenhuma reunião agendada até o momento.</div>}</section></>;
}
